language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script:
    - composer self-update
    - composer install --dev

script:
    - mkdir -p build/logs
    - make sniff test

after_script:
    - CODECLIMATE_REPO_TOKEN=92749ded80db1a2cf31084c9879f033f9ffedfcc295ec13227df2b068e7b8845 ./vendor/bin/test-reporter
